version: '3.5'

services:
  web:
    build: ./webapp
    image: webapp
    volumes:
      - data-volume:/app/uploads
      - data-volume:/app/images
    container_name: webapp
    ports:
      - "5000:5000"
    depends_on:
      - redis-server
      - mongodb

  redis-server:
    image: redis:alpine
    container_name: redis-server
    ports:
      - 6379:6379

  mongodb:
    image: mongo:4.2-bionic
    container_name: mongodb
    ports:
      - "27017:27017"

  rq-worker:
    image: jaredv/rq-docker:0.0.2
    volumes:
      - data-volume:/app/uploads
      - data-volume:/app/images
    container_name: rq-worker
    command: rq worker -u redis://redis-server:6379 high normal low
    deploy:
      replicas: 1
    depends_on:
      - redis-server
      
  rq-dashboard:
    build: ./dashboard
    image: rq-dashboard
    container_name: rq-dashboard
    ports:
      - "9181:9181"
    command: rq-dashboard -H redis-server
    depends_on:
      - redis-server
      
volumes:
  data-volume: